//! Mulberry32 — fast, deterministic 32-bit PRNG. Bit-exact port of the TS
//! implementation so seeded behavior matches across both runtimes.

pub struct Mulberry32 {
    state: u32,
}

impl Mulberry32 {
    #[must_use]
    pub fn new(seed: u32) -> Self {
        Self { state: seed }
    }

    /// Next float in [0, 1).
    pub fn next_f64(&mut self) -> f64 {
        self.state = self.state.wrapping_add(0x6D2B_79F5);
        let seed = self.state;
        let mut t = (seed ^ (seed >> 15)).wrapping_mul(1 | seed);
        t = t.wrapping_add((t ^ (t >> 7)).wrapping_mul(61 | t)) ^ t;
        f64::from(t ^ (t >> 14)) / 4_294_967_296.0
    }
}

#[cfg(test)]
mod tests {
    use super::Mulberry32;

    fn first_five(seed: u32) -> [f64; 5] {
        let mut rng = Mulberry32::new(seed);
        [
            rng.next_f64(),
            rng.next_f64(),
            rng.next_f64(),
            rng.next_f64(),
            rng.next_f64(),
        ]
    }

    // Expected values generated by running the TS mulberry32 under Node.
    #[test]
    fn matches_js_reference_seed_0() {
        assert_eq!(
            first_five(0),
            [
                0.266_429_208_684_712_65,
                0.000_329_745_700_582_861_9,
                0.223_272_027_447_819_7,
                0.146_202_147_938_311_1,
                0.467_327_822_931_110_86,
            ]
        );
    }

    #[test]
    fn matches_js_reference_seed_1() {
        assert_eq!(
            first_five(1),
            [
                0.627_073_940_588_161_3,
                0.002_735_721_180_215_478,
                0.527_447_039_959_952_2,
                0.981_050_967_471_674_1,
                0.968_377_898_214_384_9,
            ]
        );
    }

    #[test]
    fn matches_js_reference_seed_42() {
        assert_eq!(
            first_five(42),
            [
                0.601_103_751_920_163_6,
                0.448_290_558_997_541_67,
                0.852_465_793_490_409_9,
                0.669_734_041_439_369_3,
                0.174_813_898_745_924_23,
            ]
        );
    }

    #[test]
    fn matches_js_reference_seed_12345() {
        assert_eq!(
            first_five(12345),
            [
                0.979_728_267_760_947_3,
                0.306_752_264_499_664_3,
                0.484_205_421_525_985,
                0.817_934_412_509_203,
                0.509_428_369_347_006_1,
            ]
        );
    }

    #[test]
    fn matches_js_reference_seed_u32_max() {
        assert_eq!(
            first_five(4_294_967_295),
            [
                0.896_422_614_110_633_7,
                0.189_478_256_739_676,
                0.715_652_678_161_859_5,
                0.944_059_909_321_367_7,
                0.845_236_431_574_448_9,
            ]
        );
    }

    #[test]
    fn same_seed_same_sequence() {
        assert_eq!(first_five(777), first_five(777));
    }

    #[test]
    fn outputs_stay_in_unit_interval() {
        let mut rng = Mulberry32::new(999);
        for _ in 0..1000 {
            let value = rng.next_f64();
            assert!((0.0..1.0).contains(&value));
        }
    }
}
